-- CREATE TABLES
CREATE TABLE Accounts (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR2(100) NOT NULL,
    user_email VARCHAR2(100) NOT NULL,
    user_password_hash VARCHAR2(150) NOT NULL UNIQUE
);

CREATE TABLE Category (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(100) NOT NULL 
);
CREATE TABLE Expense (
    expense_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMBER(12,2) NOT NULL,
    expense_date DATE NOT NULL,
    description VARCHAR2(255),
    category_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    CONSTRAINT fk_expense_category FOREIGN KEY (category_id) REFERENCES Category(category_id),
    CONSTRAINT fk_expense_user FOREIGN KEY (user_id) REFERENCES Accounts(user_id)
);
CREATE TABLE Budget (
    budget_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    allocated_amount NUMBER(12,2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    CONSTRAINT fk_budget_category FOREIGN KEY (category_id) REFERENCES Category(category_id),
    CONSTRAINT fk_budget_user FOREIGN KEY (user_id) REFERENCES Accounts(user_id)
    
);
CREATE TABLE SavingGoal (
    goal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    target_amount NUMBER(12,2) NOT NULL,
    current_amount NUMBER(12,2) DEFAULT 0,
    deadline DATE NOT NULL,
    CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES Accounts(user_id),
    CONSTRAINT fk_goal_category FOREIGN KEY (category_id) REFERENCES Category(category_id)
);
--------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------- CRUD --------------------------------------------------------------------------------------------
--INSERT
INSERT INTO accounts (user_name, user_email, user_password_hash) VALUES ('Kenuli', 'kenuli@gmail.com', 'kenuli123');
INSERT INTO accounts (user_name, user_email, user_password_hash) VALUES ('Thashmini', 'thashmini@outlook.com', 'thash456');
INSERT INTO accounts (user_name, user_email, user_password_hash) VALUES ('Udana', 'udana@yahoo.com', 'udana678');
INSERT INTO accounts (user_name, user_email, user_password_hash) VALUES ('Ashwin', 'ashwin@gmail.com', 'ashwin079');
INSERT INTO accounts (user_name, user_email, user_password_hash) VALUES ('Tharusha', 'tharusha@outlook.com', 'tharu890');

INSERT INTO Category (category_name) VALUES ('Food');
INSERT INTO Category (category_name) VALUES ('Transportation');
INSERT INTO Category (category_name) VALUES ('Emergency Funds');
INSERT INTO Category (category_name) VALUES ('Other');

INSERT INTO Budget (category_id, user_id, allocated_amount, start_date, end_date) VALUES (1, 2, 5000.00, TO_DATE('2025-10-01', 'YYYY-MM-DD'), TO_DATE('2025-10-31', 'YYYY-MM-DD'));
INSERT INTO Budget (category_id, user_id, allocated_amount, start_date, end_date) VALUES (2, 3, 10000.00, TO_DATE('2025-10-05', 'YYYY-MM-DD'), TO_DATE('2025-10-20', 'YYYY-MM-DD'));
INSERT INTO Budget (category_id, user_id, allocated_amount, start_date, end_date) VALUES (2, 4, 50000.00, TO_DATE('2025-11-02', 'YYYY-MM-DD'), TO_DATE('2025-11-15', 'YYYY-MM-DD'));

INSERT INTO Expense (amount, expense_date, description, category_id, user_id) VALUES (1200, TO_DATE('2025-09-24', 'YYYY-MM-DD'), 'Pencils Pens', 1, 1);
INSERT INTO Expense (amount, expense_date, description, category_id, user_id) VALUES (4200, TO_DATE('2025-11-01', 'YYYY-MM-DD'), 'Shoes Tshirts', 3, 3);

INSERT INTO SavingGoal (user_id, category_id, target_amount, current_amount, deadline) VALUES (1, 1, 10000.00, 2500.00, TO_DATE('2025-12-31', 'YYYY-MM-DD')); 
INSERT INTO SavingGoal (user_id, category_id, target_amount, current_amount, deadline) VALUES (2, 3, 15000.00, 5000.00, TO_DATE('2025-11-30', 'YYYY-MM-DD')); 
INSERT INTO SavingGoal (user_id, category_id, target_amount, current_amount, deadline) VALUES (3, 2, 20000.00, 12000.00, TO_DATE('2026-01-15', 'YYYY-MM-DD')); 
INSERT INTO SavingGoal (user_id, category_id, target_amount, current_amount, deadline) VALUES (3, 2, 8000.00, 3000.00, TO_DATE('2025-12-10', 'YYYY-MM-DD')); 
INSERT INTO SavingGoal (user_id, category_id, target_amount, current_amount, deadline) VALUES (5, 1, 12000.00, 4000.00, TO_DATE('2026-02-01', 'YYYY-MM-DD')); 


----------------------------PROCEDURES---------------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE add_expense (
    p_amount NUMBER,
    p_expense_date DATE,
    p_description VARCHAR2,
    p_category_id NUMBER,
    p_user_id NUMBER
) AS
BEGIN
    INSERT INTO Expense (amount, expense_date, description, category_id, user_id) VALUES (p_amount, p_expense_date, p_description, p_category_id, p_user_id);
    DBMS_OUTPUT.PUT_LINE('Expense added successfully');
END;

CREATE OR REPLACE PROCEDURE update_budget_amount (
    p_budget_id NUMBER,
    p_new_amount NUMBER
) AS
BEGIN
    UPDATE Budget
    SET allocated_amount = p_new_amount
    WHERE budget_id = p_budget_id;

    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No record found with given budget ID');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Budget updated successfully');
    END IF;
END;

CREATE OR REPLACE PROCEDURE delete_saving_goal (
    p_goal_id NUMBER
) AS
BEGIN
    DELETE FROM SavingGoal WHERE goal_id = p_goal_id;
    DBMS_OUTPUT.PUT_LINE('Saving goal deleted successfully');
END;

CREATE OR REPLACE PROCEDURE add_user (
    p_user_name VARCHAR2,
    p_user_email VARCHAR2,
    p_user_password_hash VARCHAR2
) AS
BEGIN
    INSERT INTO Accounts (user_name, user_email, user_password_hash)
    VALUES (p_user_name, p_user_email, p_user_password_hash);
    DBMS_OUTPUT.PUT_LINE('User added successfully');
END;

---------------------------------------------------TRIGGERS---------------------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_update_saving_progress
AFTER UPDATE OF current_amount ON SavingGoal
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Saving Goal updated for user ID: ' || :NEW.user_id);
    DBMS_OUTPUT.PUT_LINE('Current Progress: ' ||
                         ROUND((:NEW.current_amount / :NEW.target_amount) * 100, 2) || '%');
END;

CREATE TABLE Expense_Log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id NUMBER,
    deleted_date DATE,
    reason VARCHAR2(255)
);
CREATE OR REPLACE TRIGGER trg_expense_delete
BEFORE DELETE ON Expense
FOR EACH ROW
BEGIN
    INSERT INTO Expense_Log (expense_id, deleted_date, reason)
    VALUES (:OLD.expense_id, SYSDATE, 'Expense deleted from system');
END;

CREATE OR REPLACE PROCEDURE monthly_expense_report (p_month NUMBER, p_year NUMBER) AS
BEGIN
    FOR rec IN (
        SELECT a.user_name, c.category_name, SUM(e.amount) AS total_spent
        FROM Expense e
        JOIN Accounts a ON e.user_id = a.user_id
        JOIN Category c ON e.category_id = c.category_id
        WHERE EXTRACT(MONTH FROM e.expense_date) = p_month
        AND EXTRACT(YEAR FROM e.expense_date) = p_year
        GROUP BY a.user_name, c.category_name
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(rec.user_name || ' - ' || rec.category_name || ' : ' || rec.total_spent);
    END LOOP;
END;

CREATE OR REPLACE PROCEDURE savings_progress_report AS
BEGIN
    FOR rec IN (
        SELECT a.user_name, c.category_name,
               s.target_amount, s.current_amount,
               ROUND((s.current_amount/s.target_amount)*100,2) AS progress
        FROM SavingGoal s
        JOIN Accounts a ON s.user_id = a.user_id
        JOIN Category c ON s.category_id = c.category_id
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(rec.user_name || ' - ' || rec.category_name || ' | Target: ' || rec.target_amount || ' | Current: ' || rec.current_amount || 
                            ' | Progress: ' || rec.progress || '%');
    END LOOP;
END;

CREATE OR REPLACE PROCEDURE sync_from_local (
    p_table_name VARCHAR2
) AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Syncing data from SQLite table: ' || p_table_name);
    DBMS_OUTPUT.PUT_LINE('Synchronization completed successfully.');
END;

------------------------------View-------------------------------------------------------
CREATE OR REPLACE VIEW Accounts_Secure AS
SELECT user_id, user_name, user_email
FROM Accounts;


CREATE OR REPLACE VIEW budget_report AS
SELECT
    b.budget_id,
    a.user_name,
    a.user_email,
    c.category_name,
    b.allocated_amount,
    b.start_date,
    b.end_date
FROM Budget b
JOIN accounts a ON b.user_id = a.user_id
JOIN Category c ON b.category_id = c.category_id;

CREATE OR REPLACE VIEW expense_report AS
SELECT
    e.expense_id,
    a.user_name,
    c.category_name,
    e.amount,
    e.description,
    e.expense_date
FROM Expense e
JOIN Accounts a ON e.user_id = a.user_id
JOIN Category c ON e.category_id = c.category_id;

CREATE OR REPLACE VIEW saving_goals_report AS
SELECT 
    s.goal_id,
    a.user_name,
    c.category_name,
    s.target_amount,
    s.current_amount,
    (s.target_amount - s.current_amount) AS remaining_amount,
    ROUND((s.current_amount / s.target_amount) * 100,2) AS progress_percentage,
    s.deadline
FROM SavingGoal s
JOIN Accounts a ON s.user_id = a.user_id
JOIN Category c ON s.category_id = c.category_id;

CREATE OR REPLACE VIEW financial_overview AS
SELECT
    a.user_name,
    c.category_name,
    NVL(SUM(b.allocated_amount), 0) AS total_budget,
    NVL(SUM(e.amount), 0) AS total_expenses,
    NVL(SUM(s.current_amount), 0) AS total_savings
FROM Accounts a
LEFT JOIN Budget b ON a.user_id = b.user_id
LEFT JOIN Expense e ON a.user_id = e.user_id
LEFT JOIN SavingGoal s ON a.user_id = s.user_id
LEFT JOIN Category c ON c.category_id = NVL(b.category_id, NVL(e.category_id, s.category_id))
GROUP BY a.user_name, c.category_name;